name: Go
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  name: Build executables
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ["windows", "linux"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: GOOS={{ matrix.os }} go build -v ./...
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          path: loki*
