name: Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master 
  push:
    branches:
      - master
jobs:
  build:
    name: Build binaries
    continue-on-error: true
    strategy:
      matrix:
        platforms: ["windows", "linux"]
    steps:
      - name: Variables
        run: |
          echo ${{ github.repository }}
          echo ${{ github.actor }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Get Dependencies
        run: go get .
      - name: Build
        run: GOOS=${{ matrix.platforms }} GOARCH=amd64 go build -o loki-${{ matrix.platforms }}

# vim: set ts=2 sts=2 sw=2 et
