name: build-packages
on:
  push:
    tags:
      - 'v**'
jobs:
  build:
    name: Build Packages
    strategy:
      matrix:
        os: ["windows", "linux"]
        package_name: ["loki.exe", "loki"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: GOOS=${{ matrix.os }} go build
      - name: Upload packages
        uses: svenstaro/upload-release-action@v2
        with: 
          overwrite: true
          file: ${{github.workspace}}/${{ matrix.package_name }}
          tag: ${{ github.ref }}
          asset_name: ${{ matrix.package_name }}

