name: build-packages
on:
  push:
    tags:
      - 'v**'
jobs:
  build:
    name: Build Packages
    strategy:
      matrix:
        os: ["windows", "linux"]
        include:
          - os: windows
            filename: loki-windows.exe
          - os: linux
            filename: loki-linux
    runs-on: ubuntu-latest
    environment: Loki
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: GOOS=${{ matrix.os }} go build -o ${{ matrix.filename }}
      - name: Upload packages
        uses: svenstaro/upload-release-action@v2
        with: 
          repo_token: ${{ secrets.GH_TOKEN }}
          overwrite: true
          file: ${{ github.workspace }}/${{ matrix.filename }}
          tag: ${{ github.ref }}
          asset_name: ${{ matrix.filename }}

