name: Release
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true
permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@01dd5d3ca463c7f10f7f4f7b4f177225ac661ee4 # v6.1.0
        with:
          gpg_private_key: ${{ secrets.SW_AUTO_GPG_KEY }}
          passphrase: ${{ secrets.SW_AUTO_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Configure Git
        run: |
          git config user.name "sw-auto"
          git config user.email "155095155+sw-auto@users.noreply.github.com"
          git config --global user.signingkey "${{ steps.import_gpg.outputs.keyid }}"
      - name: Release Please
        uses: google-github-actions/release-please-action@db8f2c60ee802b3748b512940dde88eabd7b7e01 #v3.7.13
        with:
          token: ${{ secrets.SW_AUTO_TOKEN }}
          release-type: simple
          package-name: loki 
          release-as: ${{ github.event.inputs.release_version }}
