name: Release
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true
permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895
        with:
          egress-policy: audit
      - name: Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.CUSTOM_TOKEN }}
          release-type: simple
          package-name: ${{ matrix.platforms }}
          release-as: ${{ github.event.inputs.release_version }}
