name: Release
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true
        default: '0.1.1'
      prerelease:
        description: 'Pre Release'
        required: false
        default: false
jobs:
  release:
    runs-on: ubuntu-latest
    environment: Loki
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test Keys
        run: |
          auth_token="${{ secrets.GPG_KEY }}"
          echo "auth_token length: ${#auth_token}"
      - name: Import GPG
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          git_user_signingkey: true
          git_commit_gpgsign: true
          gpg_private_key: ${{ secrets.GPG_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Configure Git
        run: |
          git config user.name ${{ vars.GH_USERNAME }}
          git config user.email ${{ vars.GH_EMAIL }}
          git config --global user.signingkey ${{ steps.gpg.outputs.keyid }}
      - name: Release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: go
          package-name: loki
          token: ${{ secrets.CUSTOM_TOKEN }}
          release-as: ${{ github.event.inputs.release_version }}

