name: Test
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Run testcases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build
      - name: Run tests
        run:  go test ./... 
